# ______ 챕터별 실행 파일 등록 ______

# add_subdirectory(chapter1)
# add_subdirectory(chapter2)
# add_subdirectory(chapter3)
# add_subdirectory(chapter4)
# add_subdirectory(chapter5)
# add_subdirectory(chapter6)
# add_subdirectory(chapter7)

# add_subdirectory(exercise7)
# add_subdirectory(exercise1)
# add_subdirectory(exercise2)
# add_subdirectory(exercise3)
# add_subdirectory(exercise4)
# add_subdirectory(exercise5)
# add_subdirectory(exercise6)
add_subdirectory(exercise7)

# add_subdirectory(extra1)
# add_subdirectory(prevmidterm)
# add_subdirectory(_MyApp_)